import React from "react";
import Head from "next/head";
import Header from "@/components/header";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Sanber Daily</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="max-w-md mx-auto">
        <Header />
      </div>
      <div className="max-w-md mx-auto shadow-xl p-2">
        {children}
      </div> */}
      <div className="max-w-md mx-auto h-screen overflow-y-auto relative">
        <div className="sticky top-0 w-full z-10">
          <Header />
        </div>
        {children}
      </div>
    </>
  );
};

export default Layout;
